// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults; the full schema is in templates/config.cue and
// the image defaults are in images.cue.
values: {}
